# Generated by Django 4.2 on 2023-05-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('freeze_time', models.DateTimeField(null=True)),
                ('contest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=50)),
                ('origin_contest', models.TextField()),
                ('sample_in', models.TextField()),
                ('sample_out', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('timeout', models.IntegerField(default=10)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('wrong_attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15)),
                ('submission', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=True)),
                ('solved', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('attempts_after_solve', models.IntegerField(default=0)),
                ('submissions', models.ManyToManyField(to='contests.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.usercontest')),
            ],
        ),
        migrations.AddField(
            model_name='usercontest',
            name='user_problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.userproblem'),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.IntegerField()),
                ('penalty_points', models.IntegerField()),
                ('problem_order', models.IntegerField()),
                ('first_solve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userproblem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='contests.contestproblem'),
        ),
    ]
