# Generated by Django 4.2 on 2023-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='origin_contest',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_name',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
