# Generated by Django 4.2 on 2023-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_problem_image_alter_contest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, to='contests.contestproblem'),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='contests.submission'),
        ),
    ]
