# Generated by Django 4.2 on 2023-05-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_problems_alter_userproblem_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.problem'),
            preserve_default=False,
        ),
    ]
