# Generated by Django 4.2 on 2023-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contestproblem_correct_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='show_stats',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='use_global_stats',
        ),
        migrations.AddField(
            model_name='contest',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='use_global_stats',
            field=models.BooleanField(default=True),
        ),
    ]
