# Generated by Django 4.2 on 2023-05-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='contest',
        ),
        migrations.AddField(
            model_name='team',
            name='contest',
            field=models.ManyToManyField(to='contests.contest'),
        ),
    ]
