# Generated by Django 4.2 on 2023-05-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_remove_team_contest_team_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='contest',
            new_name='contests',
        ),
    ]
