# Generated by Django 4.2 on 2023-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_problem_input_description_problem_output_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FileField(upload_to=''),
        ),
    ]
