# Generated by Django 4.2 on 2023-05-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_alter_submission_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contests.problem'),
            preserve_default=False,
        ),
    ]
