# Generated by Django 4.2 on 2023-05-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_userproblem_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontest',
            name='user_problems',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userproblem'),
        ),
    ]
