# Generated by Django 4.2 on 2023-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_alter_usercontest_user_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontest',
            name='user_problems',
        ),
        migrations.AddField(
            model_name='usercontest',
            name='user_problems',
            field=models.ManyToManyField(to='contests.userproblem'),
        ),
    ]
