# Generated by Django 4.2 on 2023-05-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_remove_usercontest_user_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproblem',
            name='problem',
        ),
        migrations.AddField(
            model_name='userproblem',
            name='contest_problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contests.contestproblem'),
            preserve_default=False,
        ),
    ]
