# Generated by Django 4.2 on 2023-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_alter_submission_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.TextField(),
        ),
    ]
