# Generated by Django 4.2 on 2023-05-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_usercontest_total_penalty_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontest',
            name='total_penalty_points',
        ),
        migrations.RemoveField(
            model_name='usercontest',
            name='total_solves',
        ),
    ]
