# Generated by Django 4.2 on 2023-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0023_usercontest_total_penalty_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblem',
            name='is_first_solve',
            field=models.BooleanField(default=False),
        ),
    ]
