# Generated by Django 4.2 on 2023-05-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0024_userproblem_is_first_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.contestproblem'),
            preserve_default=False,
        ),
    ]
