# Generated by Django 4.2 on 2023-06-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0029_problem_owner_group_alter_contest_contest_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contest_group',
            new_name='contest_class',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='owner_group',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='primary_group',
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('class_members', models.ManyToManyField(to='contests.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='owner_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userclass'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userclass'),
        ),
    ]
