# Generated by Django 4.2 on 2023-06-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0030_rename_contest_group_contest_contest_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userclass'),
        ),
    ]
