# Generated by Django 4.2 on 2023-06-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0031_alter_contest_contest_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.userclass'),
        ),
    ]
