# Generated by Django 4.2 on 2023-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0033_alter_userclass_class_code_alter_userproblem_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userdata',
            name='manage_contests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='manage_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
