# Generated by Django 4.2 on 2023-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0035_rename_manage_users_userdata_manage_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='is_resouce_class',
            field=models.BooleanField(default=True),
        ),
    ]
