# Generated by Django 4.2 on 2023-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0036_userclass_is_resouce_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclass',
            old_name='is_resouce_class',
            new_name='is_resource_class',
        ),
    ]
