# Generated by Django 4.2 on 2023-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0038_alter_userclass_is_resource_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='display_names',
            field=models.BooleanField(default=False),
        ),
    ]
