# Generated by Django 4.2 on 2023-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0039_contest_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('1', 'EASY'), ('2', 'MEDIUM'), ('3', 'HARD')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
