# Generated by Django 4.2 on 2023-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0040_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')]),
        ),
    ]
