# Generated by Django 4.2 on 2023-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0041_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='show_difficulty',
            field=models.BooleanField(default=False),
        ),
    ]
